CREATE DATABASE IF NOT EXISTS `data`;
USE data;


DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (

  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `image` TEXT NULL DEFAULT NULL,
  `about` TEXT NULL DEFAULT NULL,

);